### ISSUE TITLE
MPI example failing with a segmentation fault

### ISSUE THREAD

**Issue by eyalroz** [NVIDIA/multi-gpu-programming-models#13] opened 2021-11-13 10:04 UTC
I'm building the MPI example for compute capability 6.1, on Devuan GNU/Linux Chimaera (basically Debian Bullseye without systemd). When I run the program with 2 GTX 1050 Ti Boost GPUs cards, I get:
```
$ mpirun -np 2 jacobi
Single GPU jacobi relaxation: 1000 iterations on 16384 x 16384 mesh with norm check every 1 iterations
    0, 31.999022
  100, 0.897983
  200, 0.535684
  300, 0.395651
  400, 0.319039
  500, 0.269961
  600, 0.235509
  700, 0.209829
  800, 0.189854
  900, 0.173818
[bakunin:09699] Read -1, expected 65536, errno = 14
[bakunin:09700] Read -1, expected 65536, errno = 14
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node bakunin exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

**Comment by jirikraus** [comment] 2021-11-14 20:26
Can you provide some more details about your system? What MPI are you using? How is that configured?

**Comment by eyalroz** [comment] 2021-11-14 21:12
@jirikraus : Certainly. 

Kernel: 5.10.0-9-amd64 x86_64 bits: 
Desktop: Cinnamon 4.8.6 
Distro: Devuan GNU/Linux 4 (chimaera) 
Mobo: ASUSTeK model: Z170 PRO GAMING
CPU: Quad Core Intel Core i5-7600K [MCP] speed: 1042 MHz min/max: 800/4200 MHz 
Graphics:  Device-1: Intel HD Graphics 630 driver: i915 v: kernel 
           Device-2: NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nvidia v: 470.57.02 
           Device-3: NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nvidia v: 470.57.02 
Display: x11 server: X.Org 1.20.11 driver: loaded: modesetting,nvidia unloaded: fbdev,nouveau,vesa 

Library versions: 

* OpenMPI 4.1.0-10 (detected by CMake as MPI 3.1) - have not configured it manually, it's Debian's default.
* NCCL 2.11.4 - built it from sources.


-- The CUDA compiler identification is NVIDIA 11.4.48
-- The CXX compiler identification is GNU 10.2.1
-- Found CUDAToolkit: /usr/local/cuda/include (found version "11.4.48") 
-- Looking for C++ include pthread.h - found
-- Autodetected CUDA architecture(s):  6.1 6.1
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Found NCCL: /opt/nccl/lib/libnccl.so (found version "2.11.4")

**Comment by jirikraus** [comment] 2021-11-14 21:38
Thanks

> OpenMPI 4.1.0-10 (detected by CMake as MPI 3.1) - have not configured it manually, it's Debian's default.

This is likely the cause. I think the debian package is not CUDA-aware. The MPI variants of the code requires a CUDA-aware MPI. You can find information on how to build a CUDA-aware OpenMPI here: https://www.open-mpi.org/faq/?category=buildcuda 

Closing this as not a bug.

**Closed as completed by jirikraus** 2021-11-14 21:38 UTC

**Comment by eyalroz** [comment] 2021-11-14 21:55
@jirikraus : Well, perhaps you could do one of the following:

1. Check the "CUDA-awareness" of the MPI library, at run-time?
2. Check the "CUDA-awareness" of the MPI library in the Makefile?
3. Expand on what it means for MPI to be "CUDA-aware", in the README?

**Comment by jirikraus** [comment] 2021-11-29 07:45
> @jirikraus : Well, perhaps you could do one of the following:
> 
> 1. Check the "CUDA-awareness" of the MPI library, at run-time?
> 2. Check the "CUDA-awareness" of the MPI library in the Makefile?
> 3. Expand on what it means for MPI to be "CUDA-aware", in the README?

Thanks for the suggestion. I just pushed an update adding a compile and runtime check: 1aed265c11a094b6001e75416b1da061daac623c . What do you think?

**Comment by eyalroz** [comment] 2021-11-29 08:09
Haven't tested this, but it looks about right. A compile-time check is even better than a runtime check.
